#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/My201SQL
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auo: update org.hibernate.dialect.MySQL5Dialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: 949501Roza
    url: jdbc:mysql://localhost:3306/registration
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000